export const CREATE_LOCATION = 'CREATE_LOCATION';
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const LEAVE_LOCATION_OWNER = 'LEAVE_LOCATION_OWNER';
export const LOGOUT_USER = 'LOGOUT_USER';

//navbar actions
export const TOGGLE_NAV = 'TOGGLE_NAV';

//contact form actions
export const CONTACT_FORM_EMAIL_CHANGED='CONTACT_FORM_EMAIL_CHANGED';
export const CONTACT_FORM_FNAME_CHANGED='CONTACT_FORM_FNAME_CHANGED';
export const CONTACT_FORM_LNAME_CHANGED='CONTACT_FORM_LNAME_CHANGED';
export const CONTACT_FORM_SUBJECT_CHANGED='CONTACT_FORM_SUBJECT_CHANGED';
export const CONTACT_FORM_MESSAGE_CHANGED='CONTACT_FORM_MESSAGE_CHANGED';
export const CONTACT_FORM_SEND_ATTEMPT='CONTACT_FORM_SEND_ATTEMPT';
export const CONTACT_FORM_SEND_FAILURE='CONTACT_FORM_SEND_FAILURE';
export const CONTACT_FORM_SEND_SUCCESS='CONTACT_FORM_SEND_SUCCESS';
export const CONTACT_FORM_STATUS_RESET='CONTACT_FORM_STATUS_RESET';

//user form actions for register and login
export const USER_FORM_EMAIL_CHANGED='USER_FORM_EMAIL_CHANGED';
export const USER_FORM_PHONE_CHANGED='USER_FORM_PHONE_CHANGED';
export const USER_FORM_USERNAME_CHANGED='USER_FORM_USERNAME_CHANGED';
export const USER_FORM_PASSWORD_CHANGED='USER_FORM_PASSWORD_CHANGED';
export const USER_FORM_CONFIRM_PASSWORD_CHANGED='USER_FORM_CONFIRM_PASSWORD_CHANGED';
export const USER_FORM_FIRST_NAME_CHANGED='USER_FORM_FIRST_NAME_CHANGED';
export const USER_FORM_LAST_NAME_CHANGED='USER_FORM_LAST_NAME_CHANGED';
export const TOGGLE_PASSWORD_VISIBILITY='TOGGLE_PASSWORD_VISIBILITY';
export const RESET_STATUS_MESSAGE='RESET_STATUS_MESSAGE';

//user form actions for register
export const USER_REGISTER_ATTEMPT='USER_REGISTER_ATTEMPT';
export const USER_REGISTER_FAILURE='USER_REGISTER_FAILURE';
export const USER_REGISTER_SUCCESS='USER_REGISTER_SUCCESS';

//user form actions for login
export const USER_LOGIN_ATTEMPT='USER_LOGIN_ATTEMPT';
export const USER_LOGIN_FAILURE='USER_LOGIN_FAILURE';
export const USER_LOGIN_SUCCESS='USER_LOGIN_SUCCESS';

//user form actions for logout
export const USER_LOGOUT_ATTEMPT='USER_LOGOUT_ATTEMPT';
export const USER_LOGOUT_SUCCESS='USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAILURE='USER_LOGOUT_FAILURE';

//extra user form stuff
export const CHECK_USER_AUTH='CHECK_USER_AUTH';
export const SET_USER_AUTH_MESSAGE='SET_USER_AUTH_MESSAGE';

//user account actions for dashboard
export const FETCH_USER_INFO_ATTEMPT = 'FETCH_USER_INFO_ATTEMPT';
export const FETCH_USER_INFO_FAILURE = 'FETCH_USER_INFO_FAILURE';
export const FETCH_USER_INFO_SUCCESS = 'FETCH_USER_INFO_SUCCESS';