export const LOGIN_USER = 'LOGIN_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const CREATE_LOCATION = 'CREATE_LOCATION';
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const LEAVE_LOCATION_OWNER = 'LEAVE_LOCATION_OWNER';
export const LOGOUT_USER = 'LOGOUT_USER';

//navbar actions
export const TOGGLE_NAV = 'TOGGLE_NAV';

//contact form actions
export const CONTACT_FORM_EMAIL_CHANGED='CONTACT_FORM_EMAIL_CHANGED';
export const CONTACT_FORM_FNAME_CHANGED='CONTACT_FORM_FNAME_CHANGED';
export const CONTACT_FORM_LNAME_CHANGED='CONTACT_FORM_LNAME_CHANGED';
export const CONTACT_FORM_SUBJECT_CHANGED='CONTACT_FORM_SUBJECT_CHANGED';
export const CONTACT_FORM_MESSAGE_CHANGED='CONTACT_FORM_MESSAGE_CHANGED';
export const CONTACT_FORM_SEND_ATTEMPT='CONTACT_FORM_SEND_ATTEMPT';
export const CONTACT_FORM_SEND_FAILURE='CONTACT_FORM_SEND_FAILURE';
export const CONTACT_FORM_SEND_SUCCESS='CONTACT_FORM_SEND_SUCCESS';
export const CONTACT_FORM_STATUS_RESET='CONTACT_FORM_STATUS_RESET';