export const LOGIN_USER = 'LOGIN_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const CREATE_LOCATION = 'CREATE_LOCATION';
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const LEAVE_LOCATION_OWNER = 'LEAVE_LOCATION_OWNER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const TOGGLE_NAV = 'TOGGLE_NAV';